# Copyright 2021 - 2023 Transflox LLC. All rights reserved.

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: movechess
  region: ap-south-1
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: c6g.xlarge
    desiredCapacity: 1
    ssh:
      publicKeyPath: ~/.ssh/pierreneter.pub
