# Copyright 2021 - 2023 Transflox LLC. All rights reserved.

apiVersion: v1
kind: Secret
metadata:
  name: balue-shimmer
  namespace: ${NAMESPACE_RAW}
type: Opaque
data:
  ENV: ${ENV}
  PRODUCTION: ${PRODUCTION}
  MONGODB_URL: ${MONGODB_URL}
  START_CRON: ${START_CRON}
  BALUE_LISTEN: ${BALUE_LISTEN}
  DB__BALUE: ${DB__BALUE}
  DB__BALUE__COLLECTION: ${DB__BALUE__COLLECTION}
  RPC_URL: ${RPC_URL}
  RPC_WSS: ${RPC_WSS}
  NFT_CONTRACT_ADDRESS: ${NFT_CONTRACT_ADDRESS}
  IPFS_API_KEY: ${IPFS_API_KEY}
  IPFS_API_KEY_SECRET: ${IPFS_API_KEY_SECRET}
  IPFS_API_ENDPOINT: ${IPFS_API_ENDPOINT}
  NFT_STORAGE_KEY: ${NFT_STORAGE_KEY}
  ROOT_CID: ${ROOT_CID}
  FILES_DIR: ${FILES_DIR}
  TEMPLATE_DIR: ${TEMPLATE_DIR}
  AWS_ID: ${AWS_ID}
  AWS_KEY: ${AWS_KEY}
  S3_BUCKET: ${S3_BUCKET}
  S3_REGION: ${S3_REGION}
  IMAGE_PREFIX: ${IMAGE_PREFIX}
